### ISSUE TITLE
erandr single causes black screen

### ISSUE THREAD

**Issue by ukamaci** [Evidlo/erandr#1]
Here is how I get the black screen:

1. Connect an external monitor to the laptop
2. erandr right
3. Set the primary display as the external monitor
4. Disconnect the external monitor
5. erandr single

**Comment by Evidlo** [comment]
> Set the primary display as the external monitor

`erandr single` turns off all monitors except the primary, so this is the expected behavior.  You can still turn off the laptop screen in arandr without changing which monitor is the primary.

Also I think `erandr movie` does what you want.

**Comment by ukamaci** [comment]
Yes, `erandr movie` does what I want. Thanks.
